---
- hosts: all
  name: update apt
  user: root

  tasks:
  - name: apt update
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: apt upgrade
    apt:
      upgrade: dist

  - name: remove old packages and clean cache
    apt:
      autoremove: yes
      autoclean: yes
      clean: yes

  - name: check for reboot required
    register: reboot_required_file
    stat: path=/var/run/reboot-required

  - name: Send Discord Webhook
    community.general.discord:
      webhook_id: "{{ lookup('env', 'webhook_id') }}"
      webhook_token: "{{ lookup('env', 'webhook_token') }}"
      content: "APT updates completed! Reboot required: {{ reboot_required_file.stat.exists }}"