---
- name: Backup Vaultwarden data
  hosts: docker
  user: root
  gather_facts: true

  tasks:
    - name: Stop Vaultwarden container
      community.docker.docker_container:
        name: vaultwarden
        state: stopped

    - name: Create backup directory on host
      ansible.builtin.command: mkdir -p {{ lookup('env', 'backup_directory') }}
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Create backup archive of SQLite database file (shell command)
      ansible.builtin.command: |
          sqlite3 data/db.sqlite3 ".backup '{{ lookup('env', 'backup_directory') }}/db-$(date '+%Y%m%d-%H%M').sqlite3'"
      when: ansible_distribution == 'Ubuntu'
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Create backup archive of SQLite database file (VACUUM INTO, shell command)
      ansible.builtin.command: |
          sqlite3 data/db.sqlite3 "VACUUM INTO '{{ lookup('env', 'backup_directory') }}/db-$(date '+%Y%m%d-%H%M').sqlite3'"
      when: ansible_distribution == 'Ubuntu'
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Backup attachments directory (shell command)
      ansible.builtin.command: |
          cp -r {{ lookup('env', 'working_directory') }}data/attachments {{ lookup('env', 'backup_directory') }}
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Copy config.json file (shell command)
      ansible.builtin.command: |
          cp {{ vaultwarden_config_file.content }} {{ lookup('env', 'backup_directory') }}/config.json
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Backup RSA key files (shell command)
      ansible.builtin.command: |
          cp {{ lookup('env', 'working_directory') }}data/rsa_key*.der {{ lookup('env', 'backup_directory') }}
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.


   
    # - name: Encrypt backup archive with password
    #   
    #   unarchive:
    #     src: /tmp/backup.tar.gz
    #     dest: /tmp/encrypted_backup.tar.gz
    #     remote_src: no
    #   archive:
    #     path: /tmp/
    #     format: tar
    #     compression: gzip
    #     dest: /tmp/encrypted_backup.tar.gz
    #   shell:
    #     openssl enc -aes-256-cbc -in /tmp/backup.tar.gz -out /tmp/encrypted_backup.tar.gz -k {{ vaultwarden_backup_password }}

    # - name: Upload encrypted backup archive to Google Drive
    #   
    #   google_drive:
    #     service_account: "{{ gdrive_service_account }}"
    #     file_path: "/tmp/encrypted_backup.tar.gz"
    #     upload_folder: "path/to/folder/in/google/drive/"

    - name: Clean up backup files on local system
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items:
        - "{{ BACKUP_PATH }}/db-$(date '+%Y%m%d-%H%M').sqlite3"
        - "{{ BACKUP_PATH }}/config.json"
        - "{{ BACKUP_PATH }}/{{ vaultwarden_attachments_directory.basename() }}/"
        - "{{ BACKUP_PATH }}/{{ vaultwarden_attachments_directory.basename() }}/{{ item.file_name }}"
