---
- hosts: lxc_containers
  become: true
  gather_facts: true
  tasks:
    - name: Create a new user
      user:
        name: ${{ inventory.username }}
        group: ${{ inventory.group }}
        state: present